kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-gitops-argocd-application-controller-main-rbc
  namespace: "{{ _ocp4_workload_mad_roadshow_namespace }}"
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: "openshift-gitops"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-main-devhub



  argocds.argoproj.io "argocd-devhub" is forbidden:
   User "system:serviceaccount:openshift-gitops:openshift-gitops-argocd-application-controller" 
  cannot patch resource "argocds" in API group "argoproj.io" in the namespace "rhdhub2"


 checlusters.org.eclipse.che is forbidden:
  User "system:serviceaccount:openshift-gitops:openshift-gitops-argocd-application-controller" 
  cannot create resource "checlusters" in API group "org.eclipse.che" in the namespace "rhdhub2"