kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-devhub
rules:
  - verbs:
      - get
      - delete
      - patch
      - create
    apiGroups:
      - '*'
    resources:
      - '*'
  - verbs:
      - list
      - watch
    apiGroups:
      - argoproj.io
    resources:
      - applications
  - verbs:
      - list
    apiGroups:
      - ''
    resources:
      - events