apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: rhsso-rhdh
  labels:
    app: rhsso-rhdh
    app.kubernetes.io/instance: rhsso-rhdh
    app.kubernetes.io/name: rhsso-rhdh
spec:
  externalAccess:
    enabled: true
  instances: 1
