---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}
stringData:
  database-name: {{ .Values.database.name }}
  database-user: {{ .Values.database.user }}
  database-password: {{ .Values.database.password }}
type: Opaque
