---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "codeserver.fullname" . }}
  labels:
    {{- include "codeserver.labels" . | nindent 4 }}
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ include "codeserver.fullname" . }}
    weight: 100
  wildcardPolicy: None
