# Default values for tomcat-vm
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

namespacePermissions:
  # Which OpenShift user gets permissions for the namespace
  user: kubeadmin
  # Which role to grant the user on the namespace
  role: admin

resources:
  requests:
    memory: 4Gi
    cpu: 2

storage:
  pvcSize: 40Gi

image:
  url: https://gpte-public.s3.amazonaws.com/ama_demo/tomcat-mad.qcow2

nodeSelector: {}

tolerations: []

staticIP: ""
# staticIP: "10.10.10.31/24"
