kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.inventoryDb.secret.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.inventoryDb.secret.name }}
    {{- include "inventory-app.labels" . | nindent 4 }}
stringData:
  database-user: {{ .Values.inventoryDb.pgsqlUser }}
  database-password: {{ .Values.inventoryDb.pgsqlPassword }}
  database-name: {{ .Values.inventoryDb.pgsqlDatabase }}
type: Opaque
