# Default values for postgresql-database.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

namespacePermissions:
  # Which OpenShift user gets permissions for the namespace
  user: kubeadmin
  # Which role to grant the user on the namespace
  role: admin

resources:
  requests:
    memory: 4Gi
    cpu: 2

storage:
  pvcSize: 30Gi
  storageClass: gp3-csi

dataVolumeSource:
  namespace: vmimages
  name: postgresql-database
  clusterRole: datavolume-cloner

nodeSelector: {}

tolerations: []

staticIP: "10.10.10.30/24"
