kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.catalogDb.secret.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.catalogDb.secret.name }}
    {{- include "catalog-app.labels" . | nindent 4 }}
stringData:
  database-user: {{ .Values.catalogDb.pgsqlUser }}
  database-password: {{ .Values.catalogDb.pgsqlPassword }}
  database-name: {{ .Values.catalogDb.pgsqlDatabase }}
type: Opaque
