{{- if .Values.seedTackle }}
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: setup-tackle
  name: setup-tackle
  namespace: {{ .Values.namespace}}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      job-name: setup-tackle
  suspend: false
  template:
    metadata:
      labels:
        job-name: setup-tackle
    spec:
      containers:
      - image: {{ .Values.seed.repository }}:{{ .Values.seed.tag }}
        imagePullPolicy: {{ .Values.seed.pullPolicy }}
        name: setup-tackle
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: TACKLE2_USER
          value: "{{ .Values.tackle_user }}"
        - name: TACKLE2_PASSWORD
          value: "{{ .Values.tackle_password }}"
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      securityContext: {}
      terminationGracePeriodSeconds: 30
{{- end }}
