---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: tackle-operator
  namespace: {{ .Values.namespace}}
spec:
  channel: stable-v2.0
  installPlanApproval: Automatic
  name: tackle-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
