---
apiVersion: tackle.konveyor.io/v1alpha1
kind: Tackle
metadata:
  name: tackle
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  feature_auth_required: {{ .Values.tackle.feature_auth_required }}
  hub_bucket_volume_size: {{ .Values.tackle.hub_bucket_volume_size }}
  hub_database_volume_size: {{ .Values.tackle.hub_database_volume_size }}
  keycloak_database_data_volume_size: {{ .Values.tackle.keycloak_database_data_volume_size }}
  maven_data_volume_size: {{ .Values.tackle.maven_data_volume_size }}
  pathfinder_database_data_volume_size: {{ .Values.tackle.pathfinder_database_data_volume_size }}
  rwo_storage_class: {{ .Values.tackle.rwo_storage_class }}
  rwx_storage_class: {{ .Values.tackle.rwx_storage_class }}
