apiVersion: v1
kind: Service
metadata:
  name: {{ include "ocp4_workload_codeserver.fullname" . }}
  labels:
    {{- include "ocp4_workload_codeserver.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: codeserver
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    {{- include "ocp4_workload_codeserver.selectorLabels" . | nindent 4 }}
