apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ocp4_workload_codeserver.fullname" . }}
  labels:
    {{- include "ocp4_workload_codeserver.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ocp4_workload_codeserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ocp4_workload_codeserver.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "ocp4_workload_codeserver.serviceAccountName" . }}

{{- with .Values.initContainer }}
      initContainers:
      - name: init
        image: {{ .repository }}:{{ .tag }}
        imagePullPolicy: {{ .pullPolicy }}
        resources:
          requests:
            cpu: {{ .requests.cpu }}
            memory: {{ .requests.memory }}
{{- end }}
        env:
        - name: CODE_WORKSPACE_NAME
          value: {{ .Values.workspaceName | quote }}
        - name: CODE_PASSWORD
          value: {{ .Values.password | quote }}
        - name: CODE_REPOS_LIST
          value: {{ .Values.repositoryList | quote }}
        - name: CODE_EXTENSIONS_LIST
          value: {{ .Values.extensionList | quote }}
        volumeMounts:
        - name: {{ include "ocp4_workload_codeserver.fullname" . }}
          mountPath: /home/codeserver

      containers:

      - name: {{ .Chart.Name }}
{{- with .Values.mainContainer }}
        image: {{ .repository }}:{{ .tag }}
        imagePullPolicy: {{ .pullPolicy }}
        resources:
          requests:
            cpu: {{ .requests.cpu }}
            memory: {{ .requests.memory }}
{{- end }}
        ports:
        - name: codeserver
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
