---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ocp4_workload_codeserver.fullname" . }}
  labels:
    {{- include "ocp4_workload_codeserver.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
{{- if .Values.storage.storageClass }}  
  storageClassName: {{ .Values.storage.storageClass }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.pvcSize }}
