---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: codeserver-{{ .Values.user }}
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.role }}
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ .Values.user }}
