---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-clone-{{ .Values.namespace }}
  namespace: {{ .Values.imageSource.namespace }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: datavolume-cloner
