---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: {{ .Values.vmName }}
  namespace: {{ .Values.namespace }}
spec:
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: medium
        vm.kubevirt.io/os: rhel8
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/domain: {{ .Values.vmName }}
        kubevirt.io/size: medium
    spec:
      domain:
        cpu:
          cores: 2
          sockets: 2
          threads: 1
        devices:
          disks:
          - name: vol-0
            disk:
              bus: virtio
          interfaces:
          - name: net-0
            masquerade: {}
            model: virtio
          networkInterfaceMultiqueue: true
        machine:
          type: q35
        resources:
          requests:
            memory: {{ .Values.requests.memory | quote }}
            cpu: {{ .Values.requests.cpu | quote }}
      evictionStrategy: LiveMigrate
      networks:
      - name: net-0
        pod: {}
      terminationGracePeriodSeconds: 180
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      volumes:
      - name: vol-0
        dataVolume:
          name: {{ .Values.vmName }}
  dataVolumeTemplates:
  - metadata:
      name: {{ .Values.vmName }}
    spec:
      pvc:
        storageClassName: {{ .Values.storage.storageClass | quote }}
        accessModes:
        - ReadWriteOnce
        volumeMode: Block
        resources:
          requests:
            storage: {{ .Values.storage.pvcSize | quote }}
      source:
        pvc:
          namespace: {{ .Values.imageSource.namespace | quote }}
          name: {{ .Values.imageSource.name | quote }}
