kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh
data:
  app-config-rhdh.yaml: |
    app:
       # Configurations define above
    argocd:
      appLocatorMethods:
        - type: 'config'
          instances:
            - name: main
              url: ${ARGOCD_URL}
              token: ${ARGOCD_TOKEN}
    kubernetes:
      serviceLocatorMethod:
        type: 'multiTenant'
      clusterLocatorMethods:
        - type: 'config'
          clusters:
            - name: dev-cluster
              url: ${CLUSTER_URL}
              authProvider: "serviceAccount"
              skipTLSVerify: true
              serviceAccountToken: ${CLUSTER_TOKEN}
      customResources:
        - group: 'tekton.dev'
          apiVersion: 'v1beta1'
          plural: 'pipelineruns'
        - group: 'tekton.dev'
          apiVersion: 'v1beta1'
          plural: 'taskruns'
    catalog:
      rules:
        - allow: [Component, System, API, Resource, Location, Template]
      locations:
        - target: https://github.com/devhub-mad/software-templates/blob/impl/showcase-templates.yaml
          type: url
          rules:
          - allow: [Template]
      providers:
        ocm:
          env:
            kubernetesPluginRef: dev-cluster
          operate-first:
            name: dev-cluster
            url: ${CLUSTER_URL}
            serviceAccountToken: ${CLUSTER_TOKEN}
            skipTLSVerify: true
            authProvider: "serviceAccount"

    auth:
      environment: development
      providers:
        oauth2Proxy:
          development: {}
        github:
          development:
            clientId: ${GITHUB_APP_CLIENT_ID}
            clientSecret: ${GITHUB_APP_CLIENT_SECRET}

    integrations:
      github:
        - host: github.com
          apps:
            - appId: ${GITHUB_APP_APP_ID}
              clientId: ${GITHUB_APP_CLIENT_ID}
              clientSecret: ${GITHUB_APP_CLIENT_SECRET}
              webhookSecret: ${GITHUB_APP_WEBHOOK_SECRET}
              privateKey: |
                ${GITHUB_APP_PRIVATE_KEY}

    enabled:
      kubernetes: true
      github: true
      argocd: true
      githubOrg: false
      techdocs: false
      ocm: true
     

 