{{- if .Values.deployOperator -}}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: devspaces
  labels:
    {{- include "devspaces.labels" . | nindent 4 }}
spec:
  targetNamespaces:
  - {{ .Release.Namespace }}
{{- end -}}
