apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: devspaces
  namespace: openshift-operators
  annotations:
    "helm.sh/hook-weight": "-5"
spec:
  channel: {{ .Values.operatorChannel }}
  version: {{ .Values.operatorVersion }}3.9.1
  installPlanApproval: Automatic
  name: devspaces
  source: redhat-operators
  sourceNamespace: openshift-marketplace
