# Default values for tackle2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

namespacePermissions:
  # Which OpenShift user gets permissions for the namespace
  user: kubeadmin
  # Which role to grant the user on the namespace
  role: admin

# Deploy MTA Operator
deployOperator: true
operatorChannel: stable-v6.0

# Deploy Seed Job
seedTackle: false
seedJob:
  repository: quay.io/gpte-devops-automation/tackle2-setup
  tag: "v2.1.3"
  pullPolicy: IfNotPresent

# Authentication for MTA
# Leave empty for no authentication (tackleInstance.feature_auth_required: false)
tackleUser: ""
tacklePassword: ""

tackleUIServiceName: mta-ui

# Settings for the Tackle instance
tackleInstance:
  featureAuthRequired: false
  hubBucketVolumeSize: 10Gi
  hubDatabaseVolumeSize: 5Gi
  keycloakDatabaseDataVolumeSize: 1Gi
  mavenDataVolumeSize: 10Gi
  pathfinderDatabaseDataVolumeSize: 1Gi
  rwoStorageClass: ocs-storagecluster-ceph-rbd
  rwxStorageClass: ocs-storagecluster-cephfs  
