---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-clone-{{ .Release.Namespace }}
  namespace: {{ .Values.dataVolumeSource.namespace }}
  labels:
    {{- include "oracle-database.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: datavolume-cloner
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
