apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: {{ include "oracle-database.fullname" . }}
  labels:
    {{- include "oracle-database.labels" . | nindent 4 }}
spec:
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: medium
        vm.kubevirt.io/os: rhel8
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/domain: {{ include "oracle-database.fullname" . }}
        kubevirt.io/size: medium
        {{- include "oracle-database.labels" . | nindent 8 }}
    spec:
      domain:
        cpu:
          cores: 2
          sockets: 2
          threads: 1
        devices:
          disks:
          - name: vol-0
            disk:
              bus: virtio
          interfaces:
          - name: net-0
            masquerade: {}
            model: virtio
          networkInterfaceMultiqueue: true
        machine:
          type: q35
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      evictionStrategy: LiveMigrate
      networks:
      - name: net-0
        pod: {}
      terminationGracePeriodSeconds: 180
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: vol-0
        dataVolume:
          name: {{ include "oracle-database.fullname" . }}
  dataVolumeTemplates:
  - metadata:
      name: {{ include "oracle-database.fullname" . }}
    spec:
      pvc:
        storageClassName: {{ .Values.storage.storageClass }}
        accessModes:
        - ReadWriteOnce
        volumeMode: Block
        resources:
          requests:
            storage: {{ .Values.storage.pvcSize }}
      source:
        pvc:
          namespace: {{ .Values.imageSource.namespace }}
          name: {{ .Values.imageSource.name }}
