kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh
data:
  app-config-rhdh.yaml: |
    app:
       # Configurations define above
    argocd:
      appLocatorMethods:
{{- range $item := $.Values.argocd.appLocatorMethods }}
        - type: '{{ $item.type }}'
          instances:
{{- range $item1 := $item.instances }}
            - name: {{ $item1.name }}
              url: 	{{ $item1.url }}
              token: {{ $item1.token }}
{{- end }}
{{- end }}

    kubernetes:
      serviceLocatorMethod:
        type: 'multiTenant'
      clusterLocatorMethods:
        - type: 'config'
          clusters:
       {{- range $item := $.Values.clusters }}
            - name: dev-cluster
              url: {{ $item.url }}
              authProvider: "serviceAccount"
              skipTLSVerify: true
              serviceAccountToken: "{{ $item.serviceAccountToken }}"
{{- end }}
      customResources:
        - group: 'tekton.dev'
          apiVersion: 'v1beta1'
          plural: 'pipelineruns'
        - group: 'tekton.dev'
          apiVersion: 'v1beta1'
          plural: 'taskruns'
    catalog:
      rules:
        - allow: [Component, System, API, Resource, Location, Template]
      locations:
{{- range $item := $.Values.catalog.locations }}
        - target: {{ $item.target }}
          type: {{ $item.type }}
          rules:
{{- range $item1 := $item.rules }}
            - allow: {{ $item1.allow }}
{{- end }}
{{- end }}
      providers:
        ocm:
          env:
            kubernetesPluginRef: dev-cluster
          operate-first:
           {{- range $item := $.Values.clusters }}
            name: dev-cluster
            url:  {{ $item.url }}
            serviceAccountToken: "{{ $item.serviceAccountToken }}"
            skipTLSVerify: true
            authProvider: "serviceAccount"
{{- end }}


    auth:
      environment: development
      providers:
        oauth2Proxy:
          development: {}

    integrations:
      gitlab:
        - host: ""
          baseUrl: ""
          apiBaseUrl: ""
          token: ""

    enabled:
      kubernetes: true
      github: false
      argocd: true
      githubOrg: false
      techdocs: false
      ocm: true
     

 