# Source: developer-hub/charts/upstream/charts/postgresql/templates/primary/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: developer-hub-postgresql
  labels:
    {{- include "rhdh.postgresql.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
      nodePort: null
  selector:
    {{- include "rhdh.postgresql.selectorLabels" . | nindent 6 }}
---
