apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: developer-hub
  labels:
    {{- include "rhdh.labels" . | nindent 4 }}
spec:
  host:
  path: /
  port:
    targetPort: http-backend
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: developer-hub
    weight: 100
  wildcardPolicy: None
