kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-devhub
  namespace: {{ _ocp4_workload_mad_roadshow_namespace }}
rules:
  - verbs:
      - get
      - delete
      - patch
    apiGroups:
      - '*'
    resources:
      - '*'
  - verbs:
      - list
      - watch
    apiGroups:
      - argoproj.io
    resources:
      - applications
  - verbs:
      - list
    apiGroups:
      - ''
    resources:
      - events