{{- if .Values.staticIP }}
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: postgresql-net
spec:
  config: >-
    {"cniVersion":"0.3.1","type":"ovn-k8s-cni-overlay","topology":"layer2","name":
    "postgresql-net", "netAttachDefName":
    "{{ .Release.Namespace }}/postgresql-net"}
{{- end }}
