{{- if not .Values.staticIP }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql-database.fullname" . }}
  labels:
    {{- include "postgresql-database.labels" . | nindent 4 }}
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    kubevirt.io/domain: {{ include "postgresql-database.fullname" . }}
{{- end }}
