apiVersion: v1
kind: Service
metadata:
  name: {{ include "oracle-database.fullname" . }}
  labels:
    {{- include "oracle-database.labels" . | nindent 4 }}
spec:
  ports:
  - port: 1521
    protocol: TCP
    targetPort: 1521
  selector:
    kubevirt.io/domain: {{ include "oracle-database.fullname" . }}
  sessionAffinity: None
  type: ClusterIP
