apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: rhdh
  labels:
{{- include "rhdh.labels" . | nindent 4 }}
spec:
  instanceSelector:
    matchLabels:
 {{- include "rhdh.selectorLabels" . | nindent 6 }}
  realm:
    id: {{ .Values.keycloak.realm }}
    realm: {{ .Values.keycloak.realm }}
    enabled: true
    displayName: {{ .Values.keycloak.displayName }}