apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: rhdh
  labels:
{{- include "rhdh.labels" . | nindent 4 }}
spec:
  client:
    clientAuthenticatorType: client-secret
    redirectUris: https://developer-hub-{{ .Values.namespace }}.{{ .Values.app.host }}/oauth2/callback
    serviceAccountsEnabled: true
    clientId: rhdh
    defaultClientScopes:
      - profile
      - email
      - roles
    implicitFlowEnabled: false
    standardFlowEnabled: true
    consentRequired: false
    directAccessGrantsEnabled: true
  realmSelector:
    matchLabels:
 {{- include "rhdh.selectorLabels" . | nindent 6 }}
  serviceAccountClientRoles:
    realm-management:
      - query-groups
      - query-users
      - view-users
