apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "activity-tracking-simulator.name" . }}
  labels:
    {{- include "activity-tracking-simulator.labels" . | nindent 4 }}
    app.openshift.io/runtime: quarkus
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "activity-tracking-simulator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "activity-tracking-simulator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "activity-tracking-simulator.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: ACTIVITY_TRACKING_SERVICE_HOST
              value: {{ .Values.activityTrackingService.name }}:8080
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
