{{- if .Values.seedTackle -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: setup-mta
  labels:
    {{- include "mta6.labels" . | nindent 4 }}
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      job-name: setup-mta
  suspend: false
  template:
    metadata:
      labels:
        job-name: setup-mta
    spec:
      containers:
      - name: setup-mta
        image: {{ .Values.seedJob.repository }}:{{ .Values.seedJob.tag }}
        imagePullPolicy: {{ .Values.seedJob.pullPolicy }}
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: TACKLE2_USER
          value: "{{ .Values.tackleUser }}"
        - name: TACKLE2_PASSWORD
          value: "{{ .Values.tacklePassword }}"
        - name: TACKLE2_SVC
          value: "{{ .Values.tackleSvc }}"
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      securityContext: {}
      terminationGracePeriodSeconds: 30
{{- end }}
