# Default values for tackle2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

namespacePermissions:
  # Which OpenShift user gets permissions for the namespace
  user: kubeadmin
  # Which role to grant the user on the namespace
  role: admin

# Deploy RH OpenShiftDevSpaces Operator
deployOperator: true
operatorChannel: stable


# Catalogsource Settings
# Use a catalog source image snapshot
useCatalogSnapshot: false
catalogSource:
  name: redhat-operators-snapshot-rhdevspaces
  namespace: openshift-operators
  image: quay.io/gpte-devops-automation/olm_snapshot_redhat_catalog
  tag: v4.14_2023_12_18
