apiVersion: apps/v1
kind: Deployment
metadata:
  name: developer-hub
  labels:
    {{- include "rhdh.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "rhdh.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rhdh.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "rhdh.serviceAccountName" . }}
      volumes:
        - name: app-config-rhdh
          configMap:
            name: app-config-rhdh
        - name: backstage-tls
          secret:
            defaultMode: 420
            secretName: backstage-tls
        - name: backstage-app-config
          configMap:
            name: backstage-app-config
      imagePullSecrets:
        - name: mad_developer_hub_pull_secret
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: backstage-backend
          command:
            - node
            - packages/backend
          env:
            - name: APP_CONFIG_backend_listen_port
              value: '7007'
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: developer-hub-postgresql
                  key: databaseHost
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: developer-hub-postgresql
                  key: databasePort
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: developer-hub-postgresql
                  key: databaseUser
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: developer-hub-postgresql
                  key: databasePassword
            - name: POSTGRESQL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: developer-hub-postgresql
                  key: databaseAdminPassword
          ports:
            - name: backend
              containerPort: 7007
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: app-config-rhdh
              mountPath: /app/app-config-rhdh.yaml
              subPath: app-config-rhdh.yaml
            - name: backstage-app-config
              mountPath: /app/app-config-from-configmap.yaml
              subPath: app-config.yaml
          terminationMessagePolicy: File
          image: 'quay.io/rhdh/developer-hub-rhel9:1.0-8'
          args:
            - '--config'
            - app-config.yaml
            - '--config'
            - app-config.example.yaml
            - '--config'
            - app-config.example.production.yaml
            - '--config'
            - /app/app-config-rhdh.yaml
            - '--config'
            - /app/app-config-rhdh.yaml
            - '--config'
            - /app/app-config-from-configmap.yaml
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: oauth2-proxy
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: rhdh-keycloak-creds
                  key: rhsso.clientId
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: rhdh-keycloak-creds
                  key: rhsso.clientSecret
            - name: OAUTH2_PROXY_OIDC_ISSUER_URL
              value: {{ .Values.oauth2Proxy.issuerUrl }}
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: rhdh-keycloak-creds
                  key: oauth2Proxy.cookieSecret
            - name: OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY
              value: "{{ .Values.oauth2Proxy.skipTlsVerify }}"
          ports:
            - name: oauth2-proxy
              containerPort: 4180
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          image: 'quay.io/oauth2-proxy/oauth2-proxy:latest'
          args:
            - '--provider=oidc'
            - '--email-domain=*'
            - '--upstream=http://localhost:7007'
            - '--http-address=0.0.0.0:4180'
            - '--skip-provider-button'
            - '--insecure-oidc-allow-unverified-email=true'
      serviceAccount: default
      volumes:
        - name: app-config-rhdh
          configMap:
            name: app-config-rhdh
            defaultMode: 420
        - name: backstage-app-config
          configMap:
            name: backstage-app-config
            defaultMode: 420
      dnsPolicy: ClusterFirst
