apiVersion: v1
kind: Secret
metadata:
  name: developer-hub-postgresql
  labels:
    {{- include "rhdh.postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  databaseName: "{{ .Values.postgresql.database_name }}"
  databaseUser: "{{ .Values.postgresql.database_user }}"
  databasePort: "{{ .Values.postgresql.database_port }}"
{{- if .Values.postgres.database_host }}
  databaseHost: "{{ .Values.postgresql.database_host }}"
{{- else }}
  databaseHost: "{{ include "rhdh.postgresql.name" . }}"
{{- end }}
  {{- ( include "gen.postgres-password" . ) | indent 2 -}}
{{- end }}
{{- end }}

  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
