# Source: developer-hub/charts/upstream/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: developer-hub
  labels:
    {{- include "rhdh.labels" . | nindent 4 }}
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: backstage-tls
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http-backend
      port: 4180
      targetPort: oauth2-proxy
      protocol: TCP
      nodePort: null
  selector:
    {{- include "rhdh.selectorLabels" . | nindent 4 }}
