kind: Secret
apiVersion: v1
metadata:
  name: rhdh-keycloak-creds
stringData:
  oauth2Proxy.cookieSecret: {{ $.Values.oauth2Proxy.cookieSecret }}
  rhsso.clientId: {{ $.Values.keycloak.clientId }}
  rhsso.clientSecret: {{ $.Values.keycloak.clientSecret }}
type: Opaque