apiVersion: v1
kind: Secret
metadata:
  name: {{ include "order-placement.name" . }}
  labels:
    {{- include "order-placement.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  application.properties: |-
    mp.messaging.outgoing.order-event.topic={{ .Values.kafka.orderEventTopic }}
