---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tomcat.fullname" . }}
  labels:
    {{- include "tomcat.labels" . | nindent 4 }}
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    kubevirt.io/domain: {{ include "tomcat.fullname" . }}
