{{- if .Values.seedTackle }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: setup-tackle
  labels:
    {{- include "tackle2.labels" . | nindent 4 }}
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      {{- include "tackle2.selectorLabels" . | nindent 6 }}
  suspend: false
  template:
    metadata:
      labels:
        {{- include "tackle2.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: setup-tackle
        image: {{ .Values.seedJob.repository }}:{{ .Values.seedJob.tag }}
        imagePullPolicy: {{ .Values.seedJob.pullPolicy }}
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: TACKLE2_USER
          value: "{{ .Values.tackleUser }}"
        - name: TACKLE2_PASSWORD
          value: "{{ .Values.tacklePassword }}"
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      securityContext: {}
      terminationGracePeriodSeconds: 30
{{- end }}
