---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: tackle
  labels:
    {{- include "tackle2.labels" . | nindent 4 }}
spec:
  targetNamespaces:
  - {{ .Release.Namespace }}
