{{- if .Values.deployOperator -}}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: tackle-operator
  labels:
    {{- include "tackle2.labels" . | nindent 4 }}
spec:
  channel: {{ .Values.operatorChannel }}
  installPlanApproval: Automatic
  name: tackle-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
{{- end -}}
