{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "inventory-app.serviceAccountName" . }}
  labels:
    app.kubernetes.io/part-of: {{ include "inventory-app.name" . }}
{{- end }}
